name: Clojure CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup JDK
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Setup Clojure
      uses: DeLaGuardo/setup-clojure@12.5
      with:
        lein: '2.9.1' # Specify the Leiningen version you need

    - name: Cache Maven dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/.m2/repository
          ~/.gitlibs
          ~/.deps.clj
        key: cljdeps-${{ hashFiles('project.clj') }}
        restore-keys: |
          ${{ runner.os }}-m2-

    - name: Run tests
      run: lein test
